repository:
  name: target-kinesis
  description: Singer target for Amazon Kinesis and Kinesis Firehose
  private: true
  default_branch: develop
  has_issues: true
  has_wiki: false
  has_downloads: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: false

branches:
  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: false
        contexts:
          - ProntoPro/rex/pr/labels
          - ProntoPro/rex/pr/milestone
      enforce_admins: false
      restrictions:
        users: []
        teams:
          - dataeng

  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: false
        contexts:
          - ProntoPro/rex/pr/labels
          - ProntoPro/rex/pr/milestone
      enforce_admins: false
      restrictions:
        users:
          - zuc
          - zenkay
        teams: []

labels:
  - name: status/CR-NEEDED
    color: fbca04
  - name: status/CR-ISSUES-FOUND
    color: d93f0b
  - name: status/OK-TO-MERGE
    color: 00cc00
  - name: status/HELP-WANTED
    color: 9c27b0
  - name: status/NEEDS-REBASE
    color: 666633
  - name: status/ON-HOLD
    color: 365181
  - name: status/WIP
    color: bfd4f2
