pipeline:
  lint:
    image: python:3.7.1-alpine
    commands:
      - pip3 install --upgrade pip setuptools wheel
      - pip3 install pylint
      - pip3 install -e .
      - pylint -E target_kinesis/*.py
    when:
      event:
        - push

  test:
    image: python:3.7.1-alpine
    commands:
      - pip3 install --upgrade pip setuptools wheel
      - pip3 install pytest
      - pip3 install -e .
      - pytest -p no:warnings
    when:
      event:
        - push
