pipeline:
  lint:
    image: python:3.7.1-alpine
    commands:
      - pip3 install --upgrade pip setuptools wheel
      - pip3 install astroid==2.1.0
      - pip3 install pylint==2.2.2
      - pip3 install -e .
      - pylint -E target_kinesis/*.py
    when:
      event:
        - push

  test:
    image: python:3.7.1-alpine
    commands:
      - apk add --no-cache libffi-dev openssl-dev build-base
      - pip3 install --upgrade pip setuptools wheel
      - pip3 install pytest==4.2.0 pytest-cov==2.6.1 pytest-mock==1.10.1 moto==1.3.7 attrs==19.1.0
      - pip3 install -e .
      - pytest -p no:warnings --cov=target_kinesis tests/
    when:
      event:
        - push
